travis:
  secure:
    BINSTAR_TOKEN: frJUgj5ZxnXxzNtybywouvxZqdU8ddqzD3IGggVCjvKRBC/3alJ4e1x8TO/sk0AnrrWcCgFL1o2P6LgOMb0E7IR9OtQE+MjldPOGqcz6QlMzsuYnR+T9/fyvO//3eJ+BcxtDGAR1cwbNA5gtomkvdhrRCO9qd9J5OlihLjWAF3OeqQLcJLiy+oKqOx8AKB+hhqXbxm3cMnmeutJc6I7TH6Z1SjWATos7H0UHd5RzscYEQQM4orJeqarQkRmt7OwbB/yymLxNdaFcPIDYEieWBjMXyN8AZLHCAcFppgme6B76HS1gRp4o2fQwmSPn4NC8EoKBhRu3B/mLjdR7Rgdv/FV2NB3wf/nG5VfZClttyuA5Qd8wyk1BDzGR9RJU/jBiSlP86GoUVr0sOI/dyNE7FYUIP7BzpMn1joXkIKlvXIbMKTOwzsamkeOVmXYDWFdkbuKwYuL+4WNdZccEQVqKBShu3f012I0PU8VF7veM0b3/malwTx86bq/6uEjubVY+TyGPmCrIB+UPAbjrYDnqqmmiv7ZSivSWo9mm3H9XQK26b1GN0gLaeJqd+m1fuBd52hUf8RoR5vr2sYwPLAUul9UOVKtpFkR5+TrWmKTJQs2iPvQmHhovU7nS7vTUEQhx90QBPnw8akPIz0CBblzRhFzYqhoVVD6XQxxr8cPd3D0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
